name: Build and push container image
on:
    push:
        paths:
            - "docker/Dockerfile"
            - ".github/workflows/build-container.yml"
        branches:
            - main
    workflow_dispatch: # Allow manual triggering
env:
    REGISTRY: ghcr.io
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Generate lowercase image name
              id: image-name
              run: echo "value=$(echo '${{ github.repository }}/build-env' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log into Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ steps.image-name.outputs.value }}
                tags: |
                    type=raw,value=latest,enable={{is_default_branch}}
                    type=sha,prefix={{branch}}-
                    type=ref,event=branch
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: docker/Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ steps.image-name.outputs.value }}:buildcache
                cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ steps.image-name.outputs.value }}:buildcache,mode=max
